anto/urls.py
from django.urls import path

from . import views

app_name = 'anto'
urlpatterns = [
    path('', views.index, name='index'),
    path('clases/', views.clases, name='clases'),

]

biusite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('appdoku/', include('appdoku.urls')),
    path('AntoTeEntrena/', include('anto.urls')),
]

anto/models.py
from django.db import models

# Create your models here.

anto/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'anto/index.html')

def clases(request):
    return render(request, 'anto/clases.html')

anto/templates/anto/clases.html
{% extends "anto/index.html" %}
{% load static %}
{% block contenido %}

<section class="container portada">
    <div class="row align-items-center mt-5 p-3">

        <div class="col-12 d-flex flex-column">
            <h1 class="text-center text-md-start fw-bold display-5 mt-3">Tus clases son diferentes</h1>

            <p class="text-center text-md-start"><strong>AntoTeEntrena</strong> hace que tus clases únicas, desde clases
                <strong>personalizadas</strong>, reducidas, grupales, on-line, combinadas, flexibles ...</p>
        </div>
    </div>
</section>

<section class="container tarjeta">
    <div class="row justify-content-evenly align-items-center p-3">

        <div class="card col-12 col-sm-6 col-md-4 col-lg-3 p-3">
            <img src="{% static 'anto/img/clases1.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h3 class="card-title fs-5 fw-bold">Personalizadas</h3>
                <p class="card-text">Alumnos: 1</p>
                <p class="card-text">Duración: 45 min</p>
                <p class="card-text">Lugar: en domicilio</p>

                <div class="d-flex justify-content-center">
                    <a href="" class="btn btn-dark">Entrenar</a>
                </div>
            </div>
        </div>

        <div class="card col-12 col-sm-6 col-md-4 col-lg-3 p-3">
            <img src="{% static 'anto/img/clases2.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h3 class="card-title fs-5 fw-bold">Reducidas</h3>
                <p class="card-text">Alumnos: 2-3</p>
                <p class="card-text">Duración: 60 min</p>
                <p class="card-text">Lugar: domicilio</p>

                <div class="d-flex justify-content-center">
                    <a href="" class="btn btn-dark">Entrenar</a>
                </div>
            </div>
        </div>

        <div class="card col-12 col-sm-6 col-md-4 col-lg-3 p-3">
            <img src="{% static 'anto/img/clases3.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h3 class="card-title fs-5 fw-bold">Grupales</h3>
                <p class="card-text">Alumnos: 5-10</p>
                <p class="card-text">Duración: 60 min</p>
                <p class="card-text">Lugar: centros</p>

                <div class="d-flex justify-content-center">
                    <a href="" class="btn btn-dark">Entrenar</a>
                </div>
            </div>
        </div>

    </div>
</section>

{% endblock %}

anto/templates/anto/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'anto/styles.css' %}">
    <title>AntoTeEntrena</title>
</head>

<body>
    <header class="navbar navbar-expand-md fixed-top navbar-dark border-bottom navbar-fixed-top">
        <div class="container">
            <div class="d-flex justify-content-around align-items-center fs-2 fw-bold">
                <i class="bi bi-brightness-alt-high fs-1 text-white"></i>
                <a class="navbar-brand ms-1" href="{% url 'anto:index' %}">
                    <!-- <img src="{% static 'polls/img/bootstrap-logo.svg' %}" alt="Logo" width="30"
                        class="d-inline-block align-text-bottom"> -->
                    AntoTeEntrena
                </a>
            </div>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <nav class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'anto:index' %}">Anto</a>
                    </li>
                    <li class=" nav-item">
                            <a class="nav-link" href="/AntoTeEntrena/clases/">Clases</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Entrenamientos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Indumentaria</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Equipos</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li> -->
                </ul>
            </nav>
        </div>
    </header>


    <main>
        {% block contenido %}
        <section class="container portada">

            <div class="row align-items-center mt-5 p-3">

                <div class="col-12 d-flex flex-column p-3">
                    <h1 class="text-center text-md-start fw-bold display-5 mb-3">Tu entrenamiento es personalizado</h1>

                    <p class="text-center text-md-start"><strong>AntoTeEntrena</strong> es un lugar para aquellos
                        amantes del <strong>Entrenamiento Personalizado</strong>. Diseñamos tu clase, la
                        revisamos, la ejecutamos y armamos juntos un plan de entrenamiento a medida de tus necesidades y
                        objetivos.</p>

                    <p class="text-center text-md-start">Muchas veces tenemos claros nuestros objetivos, pero nos cuesta
                        alcanzarlos... Nuestra <strong>Intención es gratis</strong>, mientras que pasar a la acción nos
                        toma mucho esfuerzo.</p>

                    <p class="text-center text-md-start"><strong>AntoTeEntrena</strong> te ayudará a forlarecer tu
                        fuerza de voluntad, como un músculo, y construir así el motor hacia el cambio que queres.</p>

                    <div class="d-flex justify-content-center justify-content-md-start">
                        <a href="{% url 'anto:clases' %}" class="btn btn-dark btn-lg">Clases</a>
                    </div>
                </div>
        </section>

        <section class="formulario-contacto container shadow mt-3 p-3">

            <div class="row">

                <div class="col-md-8">
                    <h2 class="text-center text-md-start display-5 fw-bold">Quiero entrenar ...</h2>
                    <p class="text-center text-md-start">Contanos cuales son tus objetivos, que deporte haces y algo más
                        sobre vos</p>

                    <form action="" class="row">
                        <div class="form-floating mb-3 col-md-5">
                            <input type="text" class="form-control" id="nombre-usuario" placeholder="Nombre Apellido">
                            <label for="nombre-usuario">Mis objetivos son ...</label>
                        </div>
                        <div class="form-floating mb-3 col-md-5">
                            <input type="email" class="form-control" id="email-usuario" placeholder="name@example.com">
                            <label for="email-usuario">Mis deportes son ...</label>
                        </div>

                        <div class="col-md-2 d-flex justify-content-center mb-3">
                            <input type="submit" class="btn btn-dark btn-lg" value="Enviar">
                        </div>
                    </form>

                </div>

                <div class="col-md-4 d-md-flex justify-content-center align-items-center">
                    <img src="{% static 'anto/img/contacto1.jpg' %}" alt="contacto"
                        class="d-none d-md-inline-block w-75">
                </div>
            </div>
        </section>
        {% endblock %}
    </main>

    <footer>
        <div class="container bg-dark text-bg-dark">
            <div class="row justify-content-md-evenly align-items-md-center border-bottom">
                <div class="d-flex flex-column align-items-center mt-3 p-3 col-md-4">
                    <!-- <img src="{% static 'polls/img/bootstrap-logo.svg' %}" alt="logo" class="w-25"> -->
                    <i class="bi bi-brightness-alt-high fs-1"></i>
                    <span class="text-center p-2">AntoTeEntrena (c) 2023, todos los derechos reservados</span>
                </div>

                <div class="p-3 col-md-4">
                    <h3 class="text-center">AntoTeEntrena social</h3>
                    <div class="d-flex justify-content-around fs-2">
                        <i class="bi bi-whatsapp"></i>
                        <i class="bi bi-instagram"></i>
                        <!-- <i class="bi bi-facebook"></i> -->
                        <!-- <i class="bi bi-linkedin"></i> -->
                        <!-- <i class="bi bi-twitter"></i> -->
                    </div>

                </div>

                <!-- <div class="mt-3 p-3 col-md-4">
                    <h3 class="text-center text-md-start">Suscribite a nuestro Newsletter</h3>
                    <form action="" class="row">
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control text-bg-dark" id="newsletter"
                                placeholder="name@example.com">
                            <label for="newsletter">Email address</label>
                        </div>

                        <div class="d-flex justify-content-center mb-3 justify-content-md-start">
                            <input type="submit" class="btn btn-light btn-lg" value="Suscribir">
                        </div>
                    </form>
                </div> -->
            </div>

            <div class="d-flex justify-content-center p-3">
                <span>InGenios | Todos los derechos reservados</span>
            </div>
        </div>
    </footer>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>