anto/urls.py
from django.urls import path

from . import views

app_name = 'anto'
urlpatterns = [
    path('', views.index, name='index'),
    path('clases/', views.clases, name='clases'),

]

appdoku/urls.py
from django.urls import path

from . import views

app_name = 'appdoku'
urlpatterns = [
    path('', views.index, name='index'),
    path('generar/', views.generar, name='generar'),
    path('tablero/<int:tablero_id>', views.tablero, name='tablero'),
    # path('tablero/<int:tablero_id>/evaluar', views.evaluar, name='evaluar'),
    path('grilla', views.grilla, name='grilla'),
]

biusite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('appdoku/', include('appdoku.urls')),
    path('AntoTeEntrena/', include('anto.urls')),
]

appdoku/models.py
from django.db import models

class Tablero(models.Model):

    LEVEL_CHOICES = (
        ('1', 'bajo'),
        ('2', 'medio'),
        ('3', 'alto'),
    )

    SIZE_CHOICES =(
        ('3', '3x3'),
    )

    name = models.CharField(max_length=50, blank=True)
    level = models.CharField(max_length=1, default='2', choices=LEVEL_CHOICES)
    size = models.CharField(max_length=1, default='3', choices=SIZE_CHOICES)
    initial_sudoku = models.CharField(max_length=81, default='0')
    final_sudoku = models.CharField(max_length=81, default='0')
    user_sudoku = models.CharField(max_length=81, default='0')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'name: {self.name} - level: {self.level} - size: {self.size} - initial_sudoku: {self.initial_sudoku} - final_sudoku: {self.final_sudoku} - created: {self.created}'

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

appdoku/forms.py
from django import forms
from django.forms import ModelForm
from .models import Tablero



#OPCION FORM MODEL
class TableroForm(ModelForm):
    required_css_class = 'form-label'
    class Meta:
        model = Tablero
        fields = ['level', 'size']
        widgets={
                'level':forms.Select(attrs={'class':'form-select'}),
                'size':forms.Select(attrs={'class':'form-select'}),
                }
        labels = {'level': 'Nivel', 'size': 'Tamaño'}

class SudokuForm(forms.Form):
        id_0 = forms.CharField(max_length=1, required=False)
        id_1 = forms.CharField(max_length=1, required=False)
        id_2 = forms.CharField(max_length=1, required=False)
        id_3 = forms.CharField(max_length=1, required=False)
        id_4 = forms.CharField(max_length=1, required=False)
        id_5 = forms.CharField(max_length=1, required=False)
        id_6 = forms.CharField(max_length=1, required=False)
        id_7 = forms.CharField(max_length=1, required=False)
        id_8 = forms.CharField(max_length=1, required=False)
        id_9 = forms.CharField(max_length=1, required=False)
        id_10 = forms.CharField(max_length=1, required=False)
        id_11 = forms.CharField(max_length=1, required=False)
        id_12 = forms.CharField(max_length=1, required=False)
        id_13 = forms.CharField(max_length=1, required=False)
        id_14 = forms.CharField(max_length=1, required=False)
        id_15 = forms.CharField(max_length=1, required=False)
        id_16 = forms.CharField(max_length=1, required=False)
        id_17 = forms.CharField(max_length=1, required=False)
        id_18 = forms.CharField(max_length=1, required=False)
        id_19 = forms.CharField(max_length=1, required=False)
        id_20 = forms.CharField(max_length=1, required=False)
        id_21 = forms.CharField(max_length=1, required=False)
        id_22 = forms.CharField(max_length=1, required=False)
        id_23 = forms.CharField(max_length=1, required=False)
        id_24 = forms.CharField(max_length=1, required=False)
        id_25 = forms.CharField(max_length=1, required=False)
        id_26 = forms.CharField(max_length=1, required=False)
        id_27 = forms.CharField(max_length=1, required=False)
        id_28 = forms.CharField(max_length=1, required=False)
        id_29 = forms.CharField(max_length=1, required=False)
        id_30 = forms.CharField(max_length=1, required=False)
        id_31 = forms.CharField(max_length=1, required=False)
        id_32 = forms.CharField(max_length=1, required=False)
        id_33 = forms.CharField(max_length=1, required=False)
        id_34 = forms.CharField(max_length=1, required=False)
        id_35 = forms.CharField(max_length=1, required=False)
        id_36 = forms.CharField(max_length=1, required=False)
        id_37 = forms.CharField(max_length=1, required=False)
        id_38 = forms.CharField(max_length=1, required=False)
        id_39 = forms.CharField(max_length=1, required=False)
        id_40 = forms.CharField(max_length=1, required=False)
        id_41 = forms.CharField(max_length=1, required=False)
        id_42 = forms.CharField(max_length=1, required=False)
        id_43 = forms.CharField(max_length=1, required=False)
        id_44 = forms.CharField(max_length=1, required=False)
        id_45 = forms.CharField(max_length=1, required=False)
        id_46 = forms.CharField(max_length=1, required=False)
        id_47 = forms.CharField(max_length=1, required=False)
        id_48 = forms.CharField(max_length=1, required=False)
        id_49 = forms.CharField(max_length=1, required=False)
        id_50 = forms.CharField(max_length=1, required=False)
        id_51 = forms.CharField(max_length=1, required=False)
        id_52 = forms.CharField(max_length=1, required=False)
        id_53 = forms.CharField(max_length=1, required=False)
        id_54 = forms.CharField(max_length=1, required=False)
        id_55 = forms.CharField(max_length=1, required=False)
        id_56 = forms.CharField(max_length=1, required=False)
        id_57 = forms.CharField(max_length=1, required=False)
        id_58 = forms.CharField(max_length=1, required=False)
        id_59 = forms.CharField(max_length=1, required=False)
        id_60 = forms.CharField(max_length=1, required=False)
        id_61 = forms.CharField(max_length=1, required=False)
        id_62 = forms.CharField(max_length=1, required=False)
        id_63 = forms.CharField(max_length=1, required=False)
        id_64 = forms.CharField(max_length=1, required=False)
        id_65 = forms.CharField(max_length=1, required=False)
        id_66 = forms.CharField(max_length=1, required=False)
        id_67 = forms.CharField(max_length=1, required=False)
        id_68 = forms.CharField(max_length=1, required=False)
        id_69 = forms.CharField(max_length=1, required=False)
        id_70 = forms.CharField(max_length=1, required=False)
        id_71 = forms.CharField(max_length=1, required=False)
        id_72 = forms.CharField(max_length=1, required=False)
        id_73 = forms.CharField(max_length=1, required=False)
        id_74 = forms.CharField(max_length=1, required=False)
        id_75 = forms.CharField(max_length=1, required=False)
        id_76 = forms.CharField(max_length=1, required=False)
        id_77 = forms.CharField(max_length=1, required=False)
        id_78 = forms.CharField(max_length=1, required=False)
        id_79 = forms.CharField(max_length=1, required=False)
        id_80 = forms.CharField(max_length=1, required=False)


# LEVEL_CHOICES = (
#     ('1', 'bajo'),
#     ('2', 'medio'),
#     ('3', 'alto'),
#     )

# SIZE_CHOICES =(
#     ('2', '2x2'),
#     ('3', '3x3'),
#     )

# OPCION BOOTSTARP DESDE FORM
# class TableroForm(forms.Form):
#     # level = forms.CharField(max_length=3, widget=forms.Select(choices= LEVEL_CHOICES))
#     size = forms.CharField(label='Tamaño', max_length=1, widget=forms.Select(attrs={'class': 'form-select'}, choices= SIZE_CHOICES))
#     level = forms.CharField(label='Nivel', max_length=1, widget=forms.Select(attrs={'class': 'form-select'}, choices= LEVEL_CHOICES))

appdoku/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

from .models import Tablero
from .forms import TableroForm, SudokuForm

from dokusan import solvers, generators, renderers, stats
from dokusan.boards import BoxSize, Sudoku

import json

def grid_2_grid_i(grid):
    grid_i=[]
    i=0
    for fila in grid:
        grid_i_row=[]
        for item in fila:
            grid_i_row.append(("id_"+str(i),str(item)))
            i+=1
        grid_i.append(grid_i_row)
    return grid_i

def grid2cluster(grid):
    grid_cluster=[]
    for f in range(3):
        for c in range(3):
            cluster=[]
            for i in range(9):
                cluster.append(grid[3*f+i//3][3*c+i%3])
            grid_cluster.append(cluster)
    return grid_cluster          

def print_lst(lst):
    for r in lst:
        print(r)
    print("\n")


def sudoku_dic(sudoku_initial_str, sudoku_solution_str):
    sudoku_d={}
    for i in range(81):
        sudoku_d[str(i)]={}
        sudoku_d[str(i)]['row'] = i//9
        sudoku_d[str(i)]['column']= i%9
        sudoku_d[str(i)]['box']= i//27*3 + (i%9)//3
        sudoku_d[str(i)]['initial_value'] = sudoku_initial_str[i]
        sudoku_d[str(i)]['solution_value'] = sudoku_solution_str[i]
        sudoku_d[str(i)]['user_value'] = sudoku_initial_str[i]
    return sudoku_d

#--------------------------------------------------------

def index(request):
    latest_tablero_list = Tablero.objects.order_by('-created')[:20]
    context = {'latest_tablero_list': latest_tablero_list,}
    return render(request, 'appdoku/index.html', context)

def generar(request):
    # pub_date = timezone.now() - datetime.timedelta(hours=3)
    # context = {'pub_date': pub_date}
    # return render(request,'appdoku/generar.html', context)
    
    submitted = False
    if request.method == 'POST':
        form = TableroForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            
            if cd['level']=='1':
                avg_rank = 150
            elif cd['level']=='2':
                avg_rank = 300
            elif cd['level']=='3':
                avg_rank = 450
            else:
                avg_rank=150
            
            while stats.rank(sudoku := generators.random_sudoku(avg_rank)) < avg_rank:
                continue
            print(f"initial_sudoku:{sudoku}, nivel complejidad (0-500): {stats.rank(sudoku)}")

            solution = solvers.backtrack(sudoku)
            print(f'solution_sudoku: {solution}')

            sd = sudoku_dic(str(sudoku), str(solution))
            sd_sorted_by_box = sorted(sd.items(), key= lambda item: item[1]['box']) 
            sd_json=json.dumps(sd_sorted_by_box, indent=2)
            
            print(f'len sudoku_json: {len(sd_json)}')
            print(sd_json[:100])

            tablero = Tablero(name="sudoku",
                            level = cd['level'],
                            size = cd['size'],
                            initial_sudoku = str(sudoku),
                            final_sudoku = str(solution),
                            user_sudoku = str(sudoku),
                            )
            tablero.save()
            #assert False
            # return HttpResponseRedirect('?submitted=True')
            return redirect("/appdoku/tablero/"+str(tablero.id))
        else:
            print(form.errors)
    else:
        form = TableroForm()

        if 'submitted' in request.GET:
            submitted = True
    
    return render(request, 'appdoku/generar.html', {'form': form,'submitted': submitted})


def tablero(request, tablero_id):

    if request.method == 'POST':
        form = SudokuForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # print(cd)

            tablero = Tablero.objects.get(id = tablero_id)
            sudoku_solution_str = tablero.final_sudoku

            sudoku_user_str=''
            for i in range(81):
                value = cd["id_"+str(i)]
                if value in ['1','2','3','4','5','6','7','8','9']:
                    sudoku_user_str += cd["id_"+str(i)]
                elif value == '?':
                    sudoku_user_str += sudoku_solution_str[i]
                else:
                    sudoku_user_str+='0'

            tablero.user_sudoku = sudoku_user_str
            tablero.save()

        else:
            print(form.errors)

        return redirect("/appdoku/tablero/"+str(tablero_id))
    
    else:
        form = SudokuForm()
        tablero = Tablero.objects.get(id = tablero_id)
        
        sudoku_initial_str = tablero.initial_sudoku
        sudoku_solution_str = tablero.final_sudoku
        sudoku_user_str = tablero.user_sudoku

        # print(f'{sudoku_initial_str}', len(sudoku_initial_str))
        # print(f'{sudoku_user_str}', len(sudoku_user_str))
        # print(f'{sudoku_solution_str}', len(sudoku_solution_str))

        sudoku4template = []
        for i in range(81):
            if sudoku_initial_str[i] != '0':
                sudoku4template.append((i, 'id_'+str(i), str(i//27*3+(i%9)//3), sudoku_initial_str[i], 'P'))
            else:
                if sudoku_user_str[i] != '0':
                    if sudoku_user_str[i]==sudoku_solution_str[i]:
                        sudoku4template.append((i, 'id_'+str(i), str(i//27*3+(i%9)//3), sudoku_user_str[i], 'S'))
                    else:
                        sudoku4template.append((i, 'id_'+str(i), str(i//27*3+(i%9)//3), sudoku_user_str[i], 'D'))
                else:
                    sudoku4template.append((i, 'id_'+str(i), str(i//27*3+(i%9)//3), sudoku_initial_str[i], 'N'))

        sudoku4template_sorted = sorted(sudoku4template, key=lambda item: (item[2],item[0]))
        sudoku_cluster = []
        for fila in range(9):
            sudoku_cluster.append(sudoku4template_sorted[fila*9:(fila+1)*9])
        # print(sudoku_cluster)


        # for box in sudoku_cluster1:
        #     print(box) 

        # sudoku_lst=[]
        # for fila in range(9):
        #     sudoku_lst.append(list(tablero.initial_sudoku[fila*9:(fila+1)*9]))

        # sudoku_cluster = grid2cluster(grid_2_grid_i(sudoku_lst))
        # print(sudoku_cluster)
        
    return render(request, 'appdoku/tablero.html', {'form': form, 'tablero': tablero, 'sudoku_cluster': sudoku_cluster})

def grilla(request):
    return render(request, 'appdoku/grilla.html')


# def crear_juegos(request):
#     usuario = request.user
#     if request.method == 'POST':
#         nivel_partida = request.POST['nivel']
#         sudoku = generators.random_sudoku(avg_rank=150)
#         print(type(sudoku), sudoku, len(str(sudoku)))
#         print(renderers.colorful(sudoku))
#         juego = MiJuego(user_id = usuario.id,
#                         fecha = datetime.date(2022, 10, 19),
#                         nombre = request.POST['nombre'],
#                         descripcion = request.POST['descripcion'],
#                         nivel = request.POST['nivel'],
#                         sudoku_inicial = str(sudoku),
#                         sudoku_final = str(sudoku),
#                         numeros = 10,
#                         ceros = 71,
#                         progreso = 0,
#                         movimientos = 0,
#                         )
#         juego.save()
#         return redirect('/listar_juegos')
#     return render(request, 'juegos/crear_juegos.html')

appdoku/templates/appdoku/generar.html
{% extends "appdoku/index.html" %}
{% load static %}
{% block contenido %}

<section class=" container formulario-generar-tablero shadow mt-5 p-3">

    <div class="row">

        <div class="col p-3">
            <h2 class="text-center text-md-start display-5 fw-bold">Generar nuevo tablero</h2>
            <p class="text-center text-md-start">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Eligendi assumenda, aliquid numquam molestias ex amet.


                {% if submitted %}
            <p class="success">
                Muchas Gracias por generar un nuevo tablero. Mucha suerte !.
            </p>

            {% else %}

            <form enctype="multipart/form-data" action="{% url 'appdoku:generar' %}" method="post" class="row g-3" novalidate>
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="col-md-4">
                    {{ field.errors }}
                    {{ field.label_tag }} 
                    {{ field }}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <div class="col-md-2 d-flex justify-content-center align-items-center">
                    <input type="submit" class="btn btn-dark btn-lg" value="Enviar">
                </div>

            </form>
            {% endif %}

        </div>

    </div>

</section>
{% endblock %}

appdoku/templates/appdoku/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'appdoku/styles.css' %}">
    <title>appdoku</title>
</head>

<body>
    <header class="navbar navbar-expand-md fixed-top navbar-dark border-bottom navbar-fixed-top">
        <div class="container">
            <div class="d-flex justify-content-around align-items-center fs-2 fw-bold">
                <i class="bi bi-nut-fill text-white"></i>
                <a class="navbar-brand ms-1" href="{% url 'appdoku:index' %}">
                    <!-- <img src="{% static 'polls/img/bootstrap-logo.svg' %}" alt="Logo" width="30"
                        class="d-inline-block align-text-bottom"> -->
                    appdoku
                </a>
            </div>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <nav class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'appdoku:index' %}"">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Funciones</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Nosotros</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li> -->
                </ul>
            </nav>
        </div>
    </header>


    <main>
        {% block contenido %}
        <section class="container portada">

            <div class="row align-items-center mt-5 p-3">

                <!-- <div class="col-12 col-md-6 order-md-last">
                    <img src="{% static 'polls/img/butterfly.jpg' %}" class="img-fluid" alt="portada">
                </div> -->

                <div class="col-12 d-flex flex-column p-3">
                    <h1 class="text-center text-md-start fw-bold display-5">Tableros de Sudoku</h1>

                    <p class="text-center text-md-start"><strong>Appdoku</strong> es una App destinada para aquellos amantes del <strong>sudoku</strong>. Se
                        pueden generar tableros con distintos <strong>niveles de complejidad y tamaño</strong>, los mismos permaneceran 24 horas hasta que
                        automaticamente se genere la solución. Mucha suerte !</p>

                    <div class="d-flex justify-content-center justify-content-md-start">
                        <a href="{% url 'appdoku:generar' %}" class="btn btn-dark btn-lg">Generar</a>
                    </div>
                </div>
        </section>

        <section class="container tarjeta">
            <div class="row justify-content-start align-items-center p-3">
                {% if latest_tablero_list %}
                {% for tablero in latest_tablero_list %}

                <div class="card col-12 col-sm-6 col-md-4 col-lg-3 p-2">
                    <img src="{% static 'appdoku/img/sudoku.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h3 class="card-title fs-5 fw-bold">{{ tablero.name }}#{{ tablero.id }}</h3>
                        <p class="card-text">creado: {{ tablero.created }}</p>
                        <p class="card-text">nivel: {{ tablero.level }} - tamaño: {{ tablero.size }}</p>

                        <div class="d-flex justify-content-center">
                            <a href="/appdoku/tablero/{{ tablero.id }}" class="btn btn-primary">Jugar</a>
                        </div>
                    </div>
                </div>

                {% endfor %}
                {% else %}
                <p>No sudokus are available.</p>
                {% endif %}

            </div>
        </section>

        <section class="formulario-contacto container shadow mt-3 p-3">

            <div class="row">

                <div class="col-md-8">
                    <h2 class="text-center text-md-start display-5 fw-bold">Trabajemos juntos</h2>
                    <p class="text-center text-md-start">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                        Eligendi assumenda, aliquid numquam molestias ex amet.

                    <form action="" class="row">
                        <div class="form-floating mb-3 col-md-5">
                            <input type="text" class="form-control" id="nombre-usuario" placeholder="Nombre Apellido">
                            <label for="nombre-usuario">Nombre Apellido</label>
                        </div>
                        <div class="form-floating mb-3 col-md-5">
                            <input type="email" class="form-control" id="email-usuario" placeholder="name@example.com">
                            <label for="email-usuario">Email address</label>
                        </div>

                        <div class="col-md-2 d-flex justify-content-center mb-3">
                            <input type="submit" class="btn btn-dark btn-lg" value="Enviar">
                        </div>
                    </form>

                </div>

                <div class="col-md-4 d-md-flex justify-content-center align-items-center">
                    <img src="{% static 'polls/img/contacto.png' %}" alt="contacto"
                        class="d-none d-md-inline-block w-75">
                </div>
            </div>
        </section>
        {% endblock %}
    </main>

    <footer>
        <div class="container bg-dark text-bg-dark">
            <div class="row justify-content-md-between align-items-md-center border-bottom">
                <div class="d-flex flex-column align-items-center mt-3 p-3 col-md-4">
                    <!-- <img src="{% static 'polls/img/bootstrap-logo.svg' %}" alt="logo" class="w-25"> -->
                    <i class="bi bi-nut-fill fs-1"></i>
                    <span class="text-center p-2">InGenios (c) 2023, todos los derechos reservados</span>
                    <span>ingenios@gmail.com</span>
                </div>

                <div class="mt-3 p-3 col-md-4">
                    <h3 class="text-center">Nuestras Redes</h3>
                    <div class="d-flex justify-content-around fs-2">
                        <i class="bi bi-instagram"></i>
                        <i class="bi bi-facebook"></i>
                        <i class="bi bi-linkedin"></i>
                        <i class="bi bi-twitter"></i>
                    </div>


                </div>

                <div class="mt-3 p-3 col-md-4">
                    <h3 class="text-center text-md-start">Suscribite a nuestro Newsletter</h3>
                    <form action="" class="row">
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control text-bg-dark" id="newsletter"
                                placeholder="name@example.com">
                            <label for="newsletter">Email address</label>
                        </div>

                        <div class="d-flex justify-content-center mb-3 justify-content-md-start">
                            <input type="submit" class="btn btn-light btn-lg" value="Suscribir">
                        </div>
                    </form>
                </div>
            </div>

            <div class="d-flex justify-content-center p-3">
                <span>InGenios | Todos los derechos reservados</span>
            </div>
        </div>
    </footer>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>

appdoku/templates/appdoku/tablero.html
{% extends "appdoku/index.html" %}
{% load static %}
{% block contenido %}

<section class=" container mt-5 p-3">
    <div class="row mt-md-3 justify-content-center">
        <div class="col-12 col-md-5 order-md-last">
            <h2 class="text-center text-md-start display-5 fw-bold">{{ tablero.name }}#{{ tablero.id }}</h2>
            <p class="text-center text-md-start">creado: {{ tablero.created }}</p>
            <p class="text-center text-md-start">nivel: {{ tablero.level }} - tamaño: {{ tablero.size }}</p>
        </div>

        <div class="col-12 col-md-7 col-lg-5 col-xl-4">
            <form enctype="multipart/form-data" action="/appdoku/tablero/{{ tablero.id }}" method="post" class="row justify-content-center align-items-center" novalidate>
                {% csrf_token %}
                <div class="grilla gap-2">
                    {% for fila in sudoku_cluster %}
                    <div class="grilla celda">
                        {% for id, id_str, box, value, flag in fila %}
                        {% if flag == 'N' %}
                        <div class="d-flex justify-content-center align-items-center">
                            <input type="text" class="celda celda-none" id="{{ id_str }}" name="{{ id_str }}" value="" autocomplete="off">
                        </div>
                        {% elif flag == 'P' %}
                        <div class="d-flex justify-content-center align-items-center">
                            <input type="text" class="celda celda-primary"
                                id="{{ id_str }}" name="{{ id_str }}" value="{{ value }}" readonly>
                        </div>
                        {% elif flag == 'S' %}
                        <div class="d-flex justify-content-center align-items-center">
                            <input type="text" class="celda celda-success"
                                id="{{ id_str }}" name="{{ id_str }}" value="{{ value }}" readonly>
                        </div>
                        {% elif flag == 'D' %}
                        <div class="d-flex justify-content-center align-items-center">
                            <input type="text" class="celda celda-danger"
                                id="{{ id_str }}" name="{{ id_str }}" value="{{ value }}">
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
                <div class="col d-flex justify-content-end align-items-center mt-2">
                    <input type="submit" class="btn btn-dark" value="Evaluar">
                </div>
            </form>
        </div>
    </div>
</section>

<!-- <section class="container mt-3 p-3">
    <div class="row">
        <table style="width: 500px; height: 500px; padding: 20px">
            {% for fila in sudoku_lst %}
            <tr>
                {% for elemento in fila %}

                {% if elemento == '0' %}
                <td style="border: 1px solid black; text-align: center;">
                    <a href="">-</a>
                </td>
                {% else %}
                <td style="border: 1px solid black; text-align: center; background-color: gainsboro; font-size: large;">
                    {{ elemento }}
                </td>
                {% endif %}

                {% endfor %}
            </tr>
            {% endfor %}
        </table>
    </div>
</section>

<p>Progreso: ---, Movimientos: ---</p>
<a href="{% url 'appdoku:index' %}">+ Volver</a>
<p>Gracias por jugar a appDoku</p> -->

{% endblock %}